import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { db } from '../db/db';
import { computeQualificationMapping, calculateSelfDeclarationScore } from '../utils/mappingEngine';
import type { MappingResult, SelfDeclaration } from '../types';
import { AIDisclaimerBanner } from '../components/AIDisclaimerBanner';
import { 
  Award, 
  CheckCircle2, 
  AlertTriangle, 
  ArrowRight, 
  Wrench, 
  ShieldCheck, 
  FileCheck,
  ChevronRight,
  Download,
  Info
} from 'lucide-react';

export const QualificationMappingPage: React.FC = () => {
  const { activeWorker } = useAuth();
  const navigate = useNavigate();

  const [mapping, setMapping] = useState<MappingResult | null>(null);
  const [selfDeclScore, setSelfDeclScore] = useState<number>(85);

  useEffect(() => {
    const loadMappingData = async () => {
      let answers = {
        exp: 'can_do_independently',
        tools: 'can_do_independently',
        switchInstall: 'can_do_independently',
        bulbHolder: 'can_do_independently',
        socketInstall: 'can_do_independently',
        houseWiring: 'can_do_independently',
        circuitTest: 'can_do_with_help',
        powerCutOff: 'can_do_independently',
        ppeSafety: 'can_do_independently',
        independentWork: 'can_do_independently'
      };

      if (activeWorker) {
        const decl = await db.selfDeclarations.where('workerId').equals(activeWorker.id).first();
        if (decl) {
          answers = decl.answers as any;
          setSelfDeclScore(decl.score);
        }
      }

      const res = computeQualificationMapping(answers as any, activeWorker?.yearsOfExperience || 6);
      setMapping(res);
    };

    loadMappingData();
  }, [activeWorker]);

  if (!mapping) {
    return <div className="p-12 text-center text-slate-500 font-semibold">Calculating NSQF qualification mapping...</div>;
  }

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 space-y-8">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white p-8 rounded-3xl shadow-xl border border-slate-800 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-300 text-xs font-semibold border border-emerald-500/30">
              <Award className="w-4 h-4" />
              <span>NSQF Skill Recommendation Engine</span>
            </div>
            <h1 className="text-3xl font-extrabold text-white mt-2">
              Preliminary Qualification Mapping
            </h1>
            <p className="text-sm text-slate-300 mt-1">
              Candidate: <strong>{activeWorker?.fullName || 'Ravi Kumar'}</strong> ({activeWorker?.yearsOfExperience || 6} Years Experience)
            </p>
          </div>

          <div className="bg-slate-800/90 p-4 rounded-2xl border border-slate-700 text-center min-w-[140px]">
            <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">NSQF Level</p>
            <p className="text-2xl font-extrabold text-amber-400">{mapping.suggestedNSQFLevel}</p>
            <p className="text-[11px] text-slate-300 font-semibold">{mapping.suggestedQualification}</p>
          </div>
        </div>

        {/* Disclaimer Warning */}
        <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/30 text-amber-200 text-xs flex items-start gap-3">
          <Info className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
          <span>
            <strong>Note:</strong> This is a preliminary qualification recommendation generated by transparent rules. Practical assessment and final assessor approval are required before issuing formal certification.
          </span>
        </div>
      </div>

      {/* Main Grid: Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Match Percentage Card */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-3">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Skill Match Score</p>
          <div className="flex items-baseline gap-2">
            <span className="text-4xl font-extrabold text-blue-600">{mapping.matchPercentage}%</span>
            <span className="text-xs font-bold text-emerald-600">High Match</span>
          </div>
          <p className="text-xs text-slate-600">
            Based on {activeWorker?.yearsOfExperience || 6} years experience and self-declaration.
          </p>
        </div>

        {/* Confidence Level Card */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-3">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Recommendation Confidence</p>
          <div className="flex items-center gap-2">
            <span className={`px-3 py-1 rounded-lg text-sm font-extrabold ${
              mapping.confidence === 'High' ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'
            }`}>
              {mapping.confidence} Confidence
            </span>
          </div>
          <p className="text-xs text-slate-600">
            Strong alignment with Assistant Electrician trade standard criteria.
          </p>
        </div>

        {/* Action Button Card */}
        <div className="bg-slate-900 text-white p-6 rounded-2xl shadow-sm space-y-4 flex flex-col justify-between">
          <div>
            <h4 className="font-bold text-base text-white">Next Step Options</h4>
            <p className="text-xs text-slate-300 mt-1">
              Save your qualification mapping or proceed to live practical task evaluation.
            </p>
          </div>

          <div className="space-y-2">
            <button
              onClick={() => navigate(`/assessor/assessment/${activeWorker?.id || 'w-101'}`)}
              className="w-full py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow transition flex items-center justify-center gap-2"
            >
              <span>Start Practical Assessment</span>
              <ArrowRight className="w-4 h-4" />
            </button>

            <button
              onClick={() => navigate('/worker/dashboard')}
              className="w-full py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 font-semibold text-xs transition text-center"
            >
              Back to Worker Dashboard
            </button>
          </div>
        </div>
      </div>

      {/* Domain Breakdown Progress Bars */}
      <div className="bg-white p-6 sm:p-8 rounded-3xl border border-slate-200 shadow-sm space-y-6">
        <h3 className="font-bold text-lg text-slate-900 flex items-center gap-2">
          <Wrench className="w-5 h-5 text-blue-600" />
          <span>Competency Domain Breakdown</span>
        </h3>

        <div className="space-y-4">
          {[
            { label: 'Tool Identification & Handling', value: mapping.domainBreakdown.toolKnowledge, color: 'bg-blue-600' },
            { label: 'Electrical Safety & PPE Compliance', value: mapping.domainBreakdown.safetyKnowledge, color: 'bg-emerald-600' },
            { label: 'Switchboard & House Wiring Skills', value: mapping.domainBreakdown.wiringSkills, color: 'bg-indigo-600' },
            { label: 'Circuit Safety & Continuity Testing', value: mapping.domainBreakdown.testingSkills, color: 'bg-amber-500' },
            { label: 'Prior Work Experience Weight', value: mapping.domainBreakdown.experienceScore, color: 'bg-purple-600' }
          ].map((item, idx) => (
            <div key={idx} className="space-y-1.5">
              <div className="flex justify-between text-xs font-bold text-slate-700">
                <span>{item.label}</span>
                <span>{item.value}%</span>
              </div>
              <div className="w-full bg-slate-100 h-3 rounded-full overflow-hidden">
                <div
                  className={`${item.color} h-full rounded-full transition-all duration-500`}
                  style={{ width: `${item.value}%` }}
                ></div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Skills Found & Skills Requiring Practical Verification */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Skills Found */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
          <h4 className="font-bold text-slate-900 text-base flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-emerald-600" />
            <span>Identified Competencies</span>
          </h4>
          <ul className="space-y-2">
            {mapping.skillsFound.map((skill, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-slate-700 font-medium">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 shrink-0"></span>
                <span>{skill}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Skills Needing Verification */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4">
          <h4 className="font-bold text-slate-900 text-base flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-amber-500" />
            <span>Practical Verification Items</span>
          </h4>
          <ul className="space-y-2">
            {mapping.skillsRequiringVerification.slice(0, 5).map((skill, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-slate-700 font-medium">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-1.5 shrink-0"></span>
                <span>{skill}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Mandatory Policy Banner */}
      <AIDisclaimerBanner />
    </div>
  );
};
